before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
- tap:
    owner: adavidalbertson
    name: homebrew-gpair
  homepage: https://github.com/adavidalbertson/gpair
  description: A simple utility that makes it easier to share credit for collaboration on GitHub.
  dependencies:
    - git
  test: |
    system "#{bin}/gpair -h"
